### ISSUE TITLE
Виправити помилку запуску

### ISSUE THREAD

**Issue by das13** [aleks-vorgen/NCTaskManager#9]
Після запуску програми перший раз виводиться помилка, після чого програма продовжує роботу.:
```
java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(DataInputStream.java:396)
	at ua.edu.sumdu.j2se.kulykov.tasks.models.TaskIO.read(TaskIO.java:65)
	at ua.edu.sumdu.j2se.kulykov.tasks.models.TaskIO.readBinary(TaskIO.java:108)
	at ua.edu.sumdu.j2se.kulykov.tasks.controllers.IOController.readBin(IOController.java:69)
	at ua.edu.sumdu.j2se.kulykov.tasks.views.Main.<clinit>(Main.java:12)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:377)
```
Це потрібно виправити.

**Comment by aleks-vorgen** [comment]
Дефект №9
Виправлено помилку з пустим бінарним файлом, звідки читаются задачі при запуску програми
Коміт: 773a09856c6f4b34c25f28b0ffe48286abf9fe0c
